
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - argoproj.io
  resources:
  - appprojects
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - argoproj.io
  resources:
  - argocds
  verbs:
  - create
  - delete
  - get
  - update
- apiGroups:
  - devops.kubesphere.io
  resources:
  - addonStrategies
  verbs:
  - create
  - delete
  - get
  - update
- apiGroups:
  - devops.kubesphere.io
  resources:
  - applications
  verbs:
  - get
  - list
  - update
- apiGroups:
  - devops.kubesphere.io
  resources:
  - clustertemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.kubesphere.io
  resources:
  - clustertemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - devops.kubesphere.io
  resources:
  - devopsprojects
  verbs:
  - get
  - list
  - update
- apiGroups:
  - devops.kubesphere.io
  resources:
  - gitrepositories
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - devops.kubesphere.io
  resources:
  - pipelineruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.kubesphere.io
  resources:
  - pipelineruns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - devops.kubesphere.io
  resources:
  - pipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.kubesphere.io
  resources:
  - pipelines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - devops.kubesphere.io
  resources:
  - releasercontrollers
  verbs:
  - create
  - delete
  - get
  - update
- apiGroups:
  - devops.kubesphere.io
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - devops.kubesphere.io
  resources:
  - templates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.kubesphere.io
  resources:
  - templates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - devops.kubesphere.io
  resources:
  - webhooks
  verbs:
  - get
  - list
  - patch
  - update
  - watch
