apiVersion: devops.kubesphere.io/v1alpha1
kind: Application
metadata:
  name: app
spec:
  argoApp:
    project: default
    source:
      repoURL: https://github.com/kubesphere-sigs/ks-versions
      targetRevision: HEAD
      path: .
      directory:
        recurse: true
    destination:
      server: https://kubernetes.default.svc
      namespace: ks-version
    syncPolicy:
      automated:
        prune: true
