name: Build
# Need GitHub secret: DOCKER_HUB_USER, DOCKER_HUB_SECRETS, GHCR_TOKEN

on:
  push:
    branches:
      - master
      - tekton-support
      - jenkins-client-refactor
      - feat/*
      - fix/*
      - test-* # make it be easier for contributors to test
    tags:
      - 'v*.*.*'
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - "docs/**"
      - ".devcontainer/**"
      - "*.ya?ml" # ignore all yaml files(with suffix yaml or yml) in the root of the repository
      - "!codecov.yml"
      - "!.golangci.yml"
      - "!config/**"
      - "OWNERS"
      - "PROJECT"
  pull_request:
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - "docs/**"
      - ".devcontainer/**"
      - "*.ya?ml" # ignore all yaml files(with suffix yaml or yml) in the root of the repository
      - "!codecov.yml"
      - "!.golangci.yml"
      - "!config/**"
      - "OWNERS"
      - "PROJECT"
    branches:
      - 'master'
      - 'tekton-support'
      - 'jenkins-client-refactor'
      - 'feat/*'
      - 'fix/*'

jobs:
  BuildController:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Docker meta for kubesphere
        id: meta
        if: github.repository_owner == 'kubesphere'
        uses: docker/metadata-action@v3
        with:
          images: |
            kubespheredev/devops-controller
            ghcr.io/${{ github.repository_owner }}/devops-controller
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}},prefix=v
            type=sha
      - name: Docker meta for Contributors
        id: metaContributors
        if: github.repository_owner != 'kubesphere'
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/devops-controller
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}},prefix=v
            type=sha
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_SECRETS }}
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build env
        id: build_env
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]
          then
              echo "::set-output name=platforms::linux/amd64"
              echo "::set-output name=push::false"
              echo "::set-output name=load::true"
          else
              echo "::set-output name=platforms::linux/amd64,linux/arm64"
              echo "::set-output name=push::true"
              echo "::set-output name=load::false"
          fi
          echo "::set-output name=short_sha::${GITHUB_SHA::7}"
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        if: github.repository_owner == 'kubesphere'
        with:
          file: config/dockerfiles/controller-manager/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          push: ${{ steps.build_env.outputs.push }}
          load: ${{ steps.build_env.outputs.load }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ steps.build_env.outputs.platforms }}
      - name: Build and push Docker images for Contributors
        uses: docker/build-push-action@v2.4.0
        if: github.repository_owner != 'kubesphere'
        with:
          file: config/dockerfiles/controller-manager/Dockerfile
          tags: ${{ steps.metaContributors.outputs.tags }}
          push: ${{ steps.build_env.outputs.push }}
          load: ${{ steps.build_env.outputs.load }}
          labels: ${{ steps.metaContributors.outputs.labels }}
          platforms: ${{ steps.build_env.outputs.platforms }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.2.0
        if: github.event_name == 'pull_request'
        with:
          image-ref: 'ghcr.io/kubesphere/devops-controller:sha-${{ steps.build_env.outputs.short_sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  BuildAPIServer:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Docker meta for kubesphere
        id: meta
        if: github.repository_owner == 'kubesphere'
        uses: docker/metadata-action@v3
        with:
          images: |
            kubespheredev/devops-apiserver
            ghcr.io/${{ github.repository_owner }}/devops-apiserver
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}},prefix=v
            type=sha
      - name: Docker meta for Contributors
        id: metaContributors
        if: github.repository_owner != 'kubesphere'
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/devops-apiserver
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}},prefix=v
            type=sha
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_SECRETS }}
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build env
        id: build_env
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]
          then
              echo "::set-output name=platforms::linux/amd64"
              echo "::set-output name=push::false"
              echo "::set-output name=load::true"
          else
              echo "::set-output name=platforms::linux/amd64,linux/arm64"
              echo "::set-output name=push::true"
              echo "::set-output name=load::false"
          fi
          echo "::set-output name=short_sha::${GITHUB_SHA::7}"
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        if: github.repository_owner == 'kubesphere'
        with:
          file: config/dockerfiles/apiserver/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          push: ${{ steps.build_env.outputs.push }}
          load: ${{ steps.build_env.outputs.load }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ steps.build_env.outputs.platforms }}
      - name: Build and push Docker images for Contributors
        uses: docker/build-push-action@v2.4.0
        if: github.repository_owner != 'kubesphere'
        with:
          file: config/dockerfiles/apiserver/Dockerfile
          tags: ${{ steps.metaContributors.outputs.tags }}
          push: ${{ steps.build_env.outputs.push }}
          load: ${{ steps.build_env.outputs.load }}
          labels: ${{ steps.metaContributors.outputs.labels }}
          platforms: ${{ steps.build_env.outputs.platforms }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.2.0
        if: github.event_name == 'pull_request'
        with:
          image-ref: 'ghcr.io/kubesphere/devops-apiserver:sha-${{ steps.build_env.outputs.short_sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  BuildTools:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Docker meta for kubesphere
        id: meta
        if: github.repository_owner == 'kubesphere'
        uses: docker/metadata-action@v3
        with:
          images: |
            kubespheredev/devops-tools
            ghcr.io/${{ github.repository_owner }}/devops-tools
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}},prefix=v
            type=sha
      - name: Docker meta for Contributors
        id: metaContributors
        if: github.repository_owner != 'kubesphere'
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/devops-tools
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}},prefix=v
            type=sha
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_SECRETS }}
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build env
        id: build_env
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]
          then
              echo "::set-output name=platforms::linux/amd64"
              echo "::set-output name=push::false"
              echo "::set-output name=load::true"
          else
              echo "::set-output name=platforms::linux/amd64,linux/arm64"
              echo "::set-output name=push::true"
              echo "::set-output name=load::false"
          fi
          echo "::set-output name=short_sha::${GITHUB_SHA::7}"
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        if: github.repository_owner == 'kubesphere'
        with:
          file: config/dockerfiles/tools/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          push: ${{ steps.build_env.outputs.push }}
          load: ${{ steps.build_env.outputs.load }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ steps.build_env.outputs.platforms }}
      - name: Build and push Docker images for Contributors
        uses: docker/build-push-action@v2.4.0
        if: github.repository_owner != 'kubesphere'
        with:
          file: config/dockerfiles/tools/Dockerfile
          tags: ${{ steps.metaContributors.outputs.tags }}
          push: ${{ steps.build_env.outputs.push }}
          load: ${{ steps.build_env.outputs.load }}
          labels: ${{ steps.metaContributors.outputs.labels }}
          platforms: ${{ steps.build_env.outputs.platforms }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.2.0
        if: github.event_name == 'pull_request'
        with:
          image-ref: 'ghcr.io/kubesphere/devops-tools:sha-${{ steps.build_env.outputs.short_sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  UnitTest:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.4
      - name: Test
        run: |
          make test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.out
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
